name: CI
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.x'
      - run: dotnet run test
