name: Integration
on: 
  pull_request:
    branches: 
    - main
  push:
    branches: 
    - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NUGET_CERT_REVOCATION_MODE: offline
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - run: dotnet test src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocs # before formatting
      - name: Run the docs generator
        shell: pwsh
        run: |
          pushd src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocsGenerator
          dotnet run
          popd
          $output = git status --porcelain=v1 -- docs
          if ($output) {
            git diff -- docs
            throw "The docs generator has made changes to the docs folder. Please commit these changes and push them to the repository."
          }
      - run: dotnet format analyzers src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocs --diagnostics FAA0001 --severity info --verbosity normal
      - run: dotnet test src/FluentAssertions.Analyzers.FluentAssertionAnalyzerDocs # after formatting
